"""empty message

Revision ID: d1f9e8d2e7a9
Revises: 
Create Date: 2024-06-22 22:10:26.780794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f9e8d2e7a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('user_type', sa.Enum('student', 'tutor', 'admin', name='user_types'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('student',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('student_phone', sa.String(length=50), nullable=False),
    sa.Column('age', sa.String(length=15), nullable=False),
    sa.Column('education', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('tutor',
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tutor_phone', sa.String(length=50), nullable=False),
    sa.Column('tutor_description', sa.Text(), nullable=True),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('tutor_id')
    )
    op.create_table('class',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('class_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('lesson', sa.Text(), nullable=False),
    sa.Column('price', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor.tutor_id'], ),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_table('join',
    sa.Column('join_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('join_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('join')
    op.drop_table('class')
    op.drop_table('tutor')
    op.drop_table('student')
    op.drop_table('user')
    # ### end Alembic commands ###
